export const SET_CURRENT_FULLPAGE = 'SET_CURRENT_FULLPAGE'
export const SET_ACTIVE_STEP = 'SET_ACTIVE_STEP'

export const TOGGLE_SIGNUP_FORM = 'TOGGLE_SIGNUP_FORM'
export const TOGGLE_SIGNIN_FORM = 'TOGGLE_SIGNIN_FORM'
export const TOGGLE_FORGOT_PASSWORD_FORM = 'TOGGLE_FORGOT_PASSWORD_FORM'
export const TOGGLE_CHANGE_PASSWORD_FORM = 'TOGGLE_CHANGE_PASSWORD_FORM'
export const TOGGLE_CREATE_EVENT_FORM = 'TOGGLE_CREATE_EVENT_FORM'
export const TOGGLE_EVENT_DETAIL_SIDEBAR = 'TOGGLE_EVENT_DETAIL_SIDEBAR'
export const TOGGLE_USER_PROFILE_SIDEBAR = 'TOGGLE_USER_PROFILE_SIDEBAR'

export const CREATE_EVENT_FORM_NEXT = 'CREATE_EVENT_FORM_NEXT'
// USER
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE'

export const SIGNIN_REQUEST = 'SIGNIN_REQUEST'
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS'
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE'

export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST'
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS'
export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE'

export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST'
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS'
export const CHANGE_PASSWORD_FAILURE = 'CHANGE_PASSWORD_FAILURE'

export const GET_USER_DATA = 'GET_USER_DATA'

export const LOGOUT = 'LOGOUT'
export const UPDATE_PROFILE = 'UPDATE_PROFILE'

// EVENT
export const SAVE_TEMP_EVENT_DETAILS = 'SAVE_TEMP_EVENT_DETAILS'
export const SAVE_TEMP_EVENT_IMAGE = 'SAVE_TEMP_EVENT_IMAGE'
export const SAVE_TEMP_EVENT_ADDITIONAL_SETTINGS =
  'SAVE_TEMP_EVENT_ADDITIONAL_SETTINGS'
export const CLEAR_TEMP_EVENT_DATA = 'CLEAR_TEMP_EVENT_DATA'

export const TOGGLE_UPDATE_EVENT = 'TOGGLE_UPDATE_EVENT'

export const GET_ALL_EVENTS = 'GET_ALL_EVENTS'
export const GET_JOINED_EVENTS = 'GET_JOINED_EVENTS'
export const GET_ATTENDED_EVENTS = 'GET_ATTENDED_EVENTS'

export const SET_CURRENT_EVENT = 'SET_CURRENT_EVENT'
export const GET_CURRENT_EVENT_DETAILS = 'GET_CURRENT_EVENT_DETAILS'

export const CREATE_EVENT_REQUEST = 'CREATE_EVENT_REQUEST'
export const CREATE_EVENT_SUCCESS = 'CREATE_EVENT_SUCCESS'
export const CREATE_EVENT_FAILURE = 'CREATE_EVENT_FAILURE'

export const UPDATE_EVENT_REQUEST = 'UPDATE_EVENT_REQUEST'
export const UPDATE_EVENT_SUCCESS = 'UPDATE_EVENT_SUCCESS'
export const UPDATE_EVENT_FAILURE = 'UPDATE_EVENT_FAILURE'

export const JOIN_EVENT = 'JOIN_EVENT'
