export const SET_CURRENT_FULLPAGE = 'SET_CURRENT_FULLPAGE'

export const SHOW_SIGNUP_FORM = 'SHOW_SIGNUP_FORM'
export const HIDE_SIGNUP_FORM = 'HIDE_SIGNUP_FORM'

export const SHOW_SIGNIN_FORM = 'SHOW_SIGNIN_FORM'
export const HIDE_SIGNIN_FORM = 'HIDE_SIGNIN_FORM'

export const SHOW_FORGOT_PASSWORD_FORM = 'SHOW_FORGOT_PASSWORD_FORM'
export const HIDE_FORGOT_PASSWORD_FORM = 'HIDE_FORGOT_PASSWORD_FORM'

export const SHOW_CHANGE_PASSWORD_FORM = 'SHOW_CHANGE_PASSWORD_FORM'
export const HIDE_CHANGE_PASSWORD_FORM = 'HIDE_CHANGE_PASSWORD_FORM'

// USER
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE'

export const SIGNIN_REQUEST = 'SIGNIN_REQUEST'
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS'
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE'

export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST'
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS'
export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE'

export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST'
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS'
export const CHANGE_PASSWORD_FAILURE = 'CHANGE_PASSWORD_FAILURE'

export const LOGOUT = 'LOGOUT'

// EVENT
export const GET_ALL_EVENTS = 'GET_ALL_EVENTS'
export const GET_JOINED_EVENTS = 'GET_JOINED_EVENTS'
export const GET_ATTENDED_EVENTS = 'GET_ATTENDED_EVENTS'

export const GET_EVENT_DETAILS = 'GET_EVENT_DETAILS'

export const CREATE_EVENT_REQUEST = 'CREATE_EVENT_REQUEST'
export const CREATE_EVENT_SUCCESS = 'CREATE_EVENT_SUCCESS'
export const CREATE_EVENT_FAILURE = 'CREATE_EVENT_FAILURE'

export const UPDATE_EVENT_REQUEST = 'UPDATE_EVENT_REQUEST'
export const UPDATE_EVENT_SUCCESS = 'UPDATE_EVENT_SUCCESS'
export const UPDATE_EVENT_FAILURE = 'UPDATE_EVENT_FAILURE'

export const JOIN_EVENT = 'JOIN_EVENT'
